### ISSUE TITLE
Unprotect / disable protection for one or more volumes

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#1093]
# Problem
Some dynamically / imperatively defined applications, e.g., Cloud Pak for Data, need to exclude volumes from disaster recovery dynamically.

## Impact 
The impact of recovering volumes that should not be is application dependent.  For Cloud Pak for Data, recovery fails as described in #1101.

# Solution

## Scope
Sync and Async VolumeReplication volumes are addressed by this issue.  Unprotecting VolSync volumes is tracked by #879.

## Requirements
- VRG's `ReplicationState` must be `primary` to unprotect its PVCs
Unprotected PVCs like they are when deleted with #828:
- Remove `volumereplicationgroups.ramendr.openshift.io/vr-archived` annotation
- Delete its `PersistentVolume` and `PersistentVolumeClaim` object replicas from the stores specified in VRG's `Spec.S3Profiles`
- Delete its `VolumeReplication` object
- Change PV's `ReclaimPolicy` to `Delete` and remove `volumereplicationgroups.ramendr.openshift.io/vr-retained` annotation if it is set
- Remove `volumereplicationgroups.ramendr.openshift.io/pvc-protection` finalizer from PVC
- Remove its `protectedPVC` from VRG's status

## Constraints
- Limit S3 read and write rate to 1 / minute / VRG
   - Noobaa cannot tolerate a rate of 1 write / 3 sec https://github.com/RamenDR/ramen/pull/882#issuecomment-1542969558

## Assumptions
- A VRG's PVC selector is immutable
   - This is not enforced for VRGs but is for [DRPCs](https://github.com/RamenDR/ramen/blob/e0c34a700055141765a697b17720fb8b9b386c9e/api/v1alpha1/drplacementcontrol_webhook.go#L63-L68)
	 - PVC selector may be specified in a recipe which includes both a label selector and, with PR #1090, a list of namespaces
- A VRG's S3 profile names are immutable
   - This is not enforced for VRGs but is for [DRClusters](https://github.com/RamenDR/ramen/blob/e0c34a700055141765a697b17720fb8b9b386c9e/api/v1alpha1/drcluster_webhook.go#L50-52)
- A PVC may be selected by at most 1 VRG
   - This is not enforced for VRGs but there is a PR to enforce it for [DRPCs](https://github.com/RamenDR/ramen/pull/1081)
- A PVC is excluded from a VRG's protection by modifying its labels

## Unprotected PVC discovery
- VRG controller discovers PVCs to protect or unprotect due to deletion by querying the API server for PVCs matching the VRG's PVC selector
   - Deselected PVCs, to be unprotected, won't be discovered

### Approaches to discovering formerly protected PVCs
1. Get list from VRG's S3 stores
   - Query each S3 store
	 - Drawback: rate limiting required due to Noobaa issue
1. Get list from VRG's Status.ProtectedPVCs
   - VRG is already queried at the beginning of reconcile
	 - Drawback: A PVC and its PV may be stored in S3, and its VR created, but VRG status update that adds PVC may fail
1. Get list from API server
   - Label each PVC with which VRG is protecting it
	   - #627 proposes annotations, but labels leverage more efficient, built-in API server-side filtering

The first persistent step to protecting a PVC is updating it in API server with its VRG finalizer.  If this update fails, it will not be protected.  In the same update, I propose the PVC be labeled with its protecting VRG's name and namespace name.

On VRG reconcile as primary, the API server is queried for the set of VRG-owned PVCs and those currently matching the VRG's PVC selector.  Those owned but no longer matching are unprotected. To unprotect a PVC:
- Delete replicas of it and its PV from each of the VRG's S3 stores and remove associated annotation
- Unretain its PV and remove associated annotation
- Delete its VolumeReplication resource and remove associated annotation
- Delete its ProtectedPVC from VRG status
- Delete its VRG-protected finalizer

#627 proposes at most one VRG own a PVC.  This solution maintains that assumption.  Supporting multiple VRGs protecting a PVC would require:
- only the last one to unprotect it unretain its PV and remove its finalizer
- a way to label multiple owners to find formerly protected PVCs

**Comment by hatfieldbrian** [comment]
The impact of this issue to Cloud Pak for Data is recovery failure #1101

**Comment by ShyamsundarR** [comment]
> The first persistent step to protecting a PVC is updating it in API server with its VRG finalizer. If this update fails, it will not be protected. In the same update, I propose the PVC be labeled with its protecting VRG's name and namespace name.
> 
> On VRG reconcile as primary, the API server is queried for the set of VRG-owned PVCs and those currently matching the VRG's PVC selector. Those owned but no longer matching are unprotected. To unprotect a PVC:
> 
>     * Delete replicas of it and its PV from each of the VRG's S3 stores and remove associated annotation
> 
>     * Unretain its PV and remove associated annotation
> 
>     * Delete its VolumeReplication resource and remove associated annotation
> 
>     * Delete its ProtectedPVC from VRG status
> 
>     * Delete its VRG-protected finalizer

The above scheme is fine, trusting what is marked as protected on the API server and pruning those that are extra.

I suggest limiting the initial implementation to only the sync case, i.e not handle VR and VolSync backed PVC (IOW the async case). This limits the changes to the code in addressing it for the current urgent need at hand.
