### ISSUE TITLE
Consider separating Ramen API into it's own module for easier imports by other projects

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#1156]
TODO...

**Comment by nirs** [comment]
Good idea, using ramen package is very hard now, you must add tons of replacements in the go module to cope with ramen large number of kubernetes dependencies. This will help ramen e2e and kubectl-ramen plugin.

**Comment by raghavendra-talur** [comment]
Partially addressed by #1173. Will update again after the CEL changes are in.

**Comment by ShyamsundarR** [comment]
CEL changes are in, also addressed one last import in the API [here](https://github.com/RamenDR/ramen/pull/1344) closing this.
