### ISSUE TITLE
Testing DR workflows to ensure system sanity without an actual unplanned cluster loss event

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#151]
There is a desire for feature testing the recovery feature without even during an unplanned cluster loss. This is to ensure that the feature is working as desired.

The key aspect of the feature is to ensure that recovery works, but to get back to the preferred cluster without any data loss due to the test of the feature.

Currently failover will incur a data loss, and a relocate post failover would carry the data loss as it is treated as an unplanned event with no recourse to recover lost data. This needs to be addressed in some form of testing mode to ensure the feature can be tested with the failover action but relocated without data loss.

**Comment by ShyamsundarR** [comment]
On further discussions, relocate action helps test application sanity on the remote cluster and can be performed as a planned activity. There is not further need to perform a failover action and recover from last known good copy of data on the preferredCluster.
