### ISSUE TITLE
Steps to disable DR for a PlacementRule

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#152]
Steps to disable DR:
1. Check DRPC status
    - It should be Available and PeerReady
      - This would signal, that the remote end is also healthy, and if we disable garbage collection would be done properly
      - If it is not, then just disallow the operation stating DRPC is not in a stable state for disabling
        - This would also cover when any DR action is in progress, as one of Available/PeerReady would not be true
      - A corner case can be disable as remote cluster is unrecoverable and the user is getting rid of DR as such, but that may have to wait and be done differently (for example, marking the remote DRCluster as out of commission and then proceed with deletion)
2. Delete DRPC
    - Wait for DRPC to be deleted, so that it finishes all garbage collection
    - While this is not a strict requirement, it maybe useful to keep the app DR protected if DRPC is being deleted
3. Update the placement to remove the Ramen annotation

In a sense, 1 should not be required, as DRPC deletion should ensure the conditions are met before proceeding with the cleanup. There are a few issues to address:

## Additional issues that may needed to complete this

- [ ] https://github.com/RamenDR/ramen/issues/716
- [ ] https://github.com/RamenDR/ramen/issues/715
- [ ] (maybe) https://github.com/RamenDR/ramen/issues/574

**Comment by nirs** [comment]
PlacemmentRule was replaced by Placement, we will not document the steps for PlacementRule.
