### ISSUE TITLE
VRG required faking S3 region to avoid empty region values with uploading PVs

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#153]
~~Wait for "managed resources" to change state and trigger a reconcile, rather than re-queuing ourselves~~

For DRPC say PV MW status, or MCV of VRG. Annotations as SetControllerReference does not cross namespaces.

(from HackMD list)

**Comment by ShyamsundarR** [comment]
@vdeenadh do we need this, or can be closed?

**Comment by vdeenadh** [comment]
This issue is addressed via #261 and can be closed. 

The [AWS SDK for Go webpage](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html) states the following:
>  Most settings are optional. However, for each service client, you must specify an AWS Region and your credentials.
