### ISSUE TITLE
createVR should add err into the error message

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#154]
(from HackMD list)

**Comment by ShyamsundarR** [comment]
The error returns in [here](https://github.com/RamenDR/ramen/blob/855fea5c4c8f9f4d2fcdfb91d49a3cc5de39be78/controllers/volumereplicationgroup_controller.go#L1134-L1143) are not adding the error returned by the called functions in the message, which helps debug issues when an actual error occurs.

@raghavendrabhat request that these be added in the error return.
