### ISSUE TITLE
Fix sporadic CI failures

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#156]
(from HackMD list)

**Comment by ShyamsundarR** [comment]
The sporadic failure is caused as follows:

- Initial placement is completed (where spec has no preferredCluster)
- The test case for "Should not failover to Secondary (WestManagedCluster) till PV manifest is applied" starts and changes the cloned placement rule
- DRPC is reconciled again, and as clone placement points to west, and there is no preferred cluster in the spec, the workload starts getting placed to the west cluster

The above caused the failure in the tests.

The potential fix for the same is to not look at cloned placement rule if user placement rule is already placed. IOW,
- Initially userPl is empty and filled with a clone placement rule determined preferred cluster
- On further clone placement rule changes, and any forced/timed DRPC reconciliation should not change the user placement rule decision

**Comment by ShyamsundarR** [comment]
This is fixed (for known CI failures) with #197
