### ISSUE TITLE
e2e: Improper use of error formatting

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#1618]
We have many instances like this:

```go
fmt.Errorf("drpc " + drpcName + " is not ready yet before timeout, fail")
```

Should use:

```go
fmt.Errorf("drpc %q is not ready yet before timeout, fail", drpcName)
```

Notes: Use %q to get clear values in logs, and detect values with leading or trailing whitespace

**Comment by alonsofabila-dev** [comment]
hi, can i work on this?

**Comment by nirs** [comment]
@alonsofabila-dev sure, welcome to ramen!

If you want to test you changes locally see https://github.com/RamenDR/ramen/blob/main/docs/devel-quick-start.md

If you have issues setting up testing environment locally, our CI will run your changes with one.

**Comment by alonsofabila-dev** [comment]
this changes are only under the e2e directory?

**Comment by nirs** [comment]
> this changes are only under the e2e directory?

We may have the same issue in other places, but I think it is best to focus on the e2e directory for now.
