### ISSUE TITLE
The destination S3 store/location may need to be fed per VRG CR.

### ISSUE THREAD

**Issue by vdeenadh** [RamenDR/ramen#19]
(future) The destination S3 store/location may need to be fed per VRG CR.

- A cluster may be in a DR relationship across different peer groups
- Each peer group hence may have a different S3 bucket(?) or target location
- URL should hence be configured per VRG
- BUT, access tokens to the S3 store would need to still come from secrets

Also, this is possibly another case where we need a notion of DRClusterPeers CRD to group DR clusters.

Veera's follow up questions:
- Will AVR create the DRClusterPeers or OCS?
- Is the S3 url is an AVR spec field? 

_Originally posted by @ShyamsundarR in https://github.com/RamenDR/ramen/pull/15#discussion_r595948065_

**Comment by ShyamsundarR** [comment]
These are technically closed, and latest work to move these out of DRPC is being done in #117
