### ISSUE TITLE
S3Store backup failure handling across VRG and DRPC

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#193]
While discussing S3Store unavailability in a case where `east` cluster backs up PVs to `west` and vice-versa, on a failover, VRG will not promote the volumes to `Primary` as the alternate cluster is down and the backup will fail.

Towards this the following possible actions needs to be taken,
- Change VR state first and backup PVs later in VRG
- DRPC needs to check if Primary VRG is healthy before taking action on relocate
- On a failover action, user needs to ensure DRPC last known status  (which would carry VRG last known status) has met all required Conditions to recover the workload on an alternate cluster

**Comment by vdeenadh** [comment]
I believe this issue can be closed given that it is addressed in commit  https://github.com/RamenDR/ramen/commit/074a46438f52c9c41d9cae97631a3e7b1f0b8d98.
