### ISSUE TITLE
Ramen hub-operator should proceed to relocate the app only if both of its data and cluster data are up-to-date on the target cluster 

### ISSUE THREAD

**Issue by vdeenadh** [RamenDR/ramen#244]
1.  When the user relocates an app to a target cluster via `DRPC.spec.DRAction: relocate`, Ramen hub-operator should perform the relocate operation only if the app's data and cluster data are fully replicated to the target cluster; this is required to ensure that there is no data loss during the relocate action.

2. In case, the relocate operation fails because the target cluster is not fully caught up with data and cluster data, the user should be able to clear the relocate DRAction to deploy the application back to where it was running before. 
  - If the app was previously deployed to a cluster that is not the home cluster, do we need a new DRAction to redeploy back to that cluster?

**Comment by ShyamsundarR** [comment]
The target cluster is fully caught up at present when each VR reports it s`Degraded` condition as `False`. Which is only reported as `False` (currently) when both/all ends of the replication are Secondary. In a situation where one end is Primary and the other Secondary, `Degraded` stays as `True` till both become `Secondary` and have caught up with the other.

We need to understand if VolRep would report `Degraded` as `False` if one end is Primary and the other Secondary, and if not look at additional VRG condition to represent the same, and hence act accordingly at DRPC reconciler to take the required action (failing a relocate, etc.)

**Comment by BenamarMk** [comment]
VolRep should report `Degraded` as `True` in only one case.  Where you have a `Primary` only.  In all other cases, it should report `Degraded` as `False`.

**Comment by ShyamsundarR** [comment]
DRPC to check if Secondary state (post current cluster is moved from Primary to Secondary) as reported by VRG, is "healthy", i.e final sync is done (i.e VolRep Resyncing is false) before proceeding with the relocation (i.e changing the userPlacementRule)

**Comment by ShyamsundarR** [comment]
Changes to VR conditions is now [fixed](https://github.com/csi-addons/volume-replication-operator/pull/113)

From a DRPC/VRG perspective we now need the following changes:
- VRG is currently reporting `DataReady` as true under the following conditions:
    - VR reports: Degraded: True and Resync: True
        - This is useful when there is a known `Primary`, for example post failover, or even post relocate before VRG deletion on old secondary (as the condition may change based on VR catching up to a new primary elsewhere)
    - VR reports: Degraded: False and Resync: False
        - This is useful when there are no known primaries and a final sync of data is complete across secondaries
- DRPC processes `DataReady` to relocate
We need:
- VRG to report `DataReady` based on if we want a final sync complete or we just want it resyncing

One option is for DRPC to send in a spec field stating what state it wants the replication in, which is currently `Primary'|'Secondary', and say add 'StableSecondary`, which can then be used by VRG to check for appropriate tuple of conditions and report `DataReady`

**Comment by vdeenadh** [comment]
I was think along the lines of how VRG distinguishes ClusterDataReady vs ClusterDataProtected, VRG should also distinguish between DataReady vs DataProtected.

**Comment by ShyamsundarR** [comment]
> I was thinking along the lines of how VRG distinguishes ClusterDataReady vs ClusterDataProtected, VRG should also distinguish between DataReady vs DataProtected.

Ack, should have added this as one of the options, i.e add a condition to VRG for the distinction.
