### ISSUE TITLE
Do not use a map to list PVC conditions in VRG status

### ISSUE THREAD

**Issue by vdeenadh** [RamenDR/ramen#248]
Given that maps are not recommended in APIs, The [PVC conditions map](https://github.com/RamenDR/ramen/blob/dbf60fce682337da0d1181e74a54672201f14aa8/api/v1alpha1/volumereplicationgroup_types.go#L98) in VRG status should be changed to a list.

**Comment by raghavendrabhat** [comment]
Fixed by https://github.com/RamenDR/ramen/pull/253
