### ISSUE TITLE
Change VRG "replicating" condition on Primary to "Ready" condition

### ISSUE THREAD

**Issue by vdeenadh** [RamenDR/ramen#249]
VRG in primary mode does not have information from VR on whether replication with secondary is active or not.  Hence, the current "replicating" condition is misnomer.

On the other hand, VRG on secondary can get some information from VR on whether replication with primary is active or not.  Hence, its condition could report "replicating" or "resyncing", states correctly.

**Comment by ShyamsundarR** [comment]
@vdeenadh and @raghavendrabhat This can be closed as the PR is merged?

**Comment by raghavendrabhat** [comment]
PR #262 addresses this issue. Closing it.
