### ISSUE TITLE
[Coding style] Function definitions before/after use

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#28]
This is to discuss which style we want to follow when defining newer functions.

- Define pre the function that is using the same
- Define post the function that is using the same

This does assume function is defined in the same file.

We now have 2 differing styles in these files, [vrg-reconciler](https://github.com/RamenDR/ramen/blob/main/controllers/applicationvolumereplication_controller.go) and [avr-reconciler](https://github.com/RamenDR/ramen/blob/main/controllers/volumereplicationgroup_controller.go)

My vote is for the latter as in the avr-reconciler, IOW "Define post the function that is using the same".

If we agree, we can refactor vrg-reconciler subsequently to align with the same.

NOTE: Did not find a linter to enforce this yet!

**Comment by ShyamsundarR** [comment]
@BenamarMk @raghavendrabhat @vdeenadh @tjanssen3

**Comment by raghavendrabhat** [comment]
Agree. Also, one of the other things that can be decided is the naming convention. In VRG, some functions start with capital letters and some with small letters. This question is also raised as a comment in one of the PRs. If there is a convention that has to be followed with respect to the naming of the functions and variables, that would also be better.

**Comment by BenamarMk** [comment]
Well, the function that start with a capital letter that is public.  The one that is start with lowercase letter is private.  I tend to start everything with lowercase unless there is a need for public API.
