### ISSUE TITLE
s3 secret data visible in last-applied-configuration annotation

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#280]
It seems the intent of a `secret` is to make some data secret, however the `last-applied-configuration` annotation reveals secret data:
```
$ kubectl --context cluster1 get secrets -n ramen-system s3secret -oyaml
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"s3secret","namespace":"ramen-system"},"stringData":{"AWS_ACCESS_KEY_ID":"minio","AWS_SECRET_ACCESS_KEY":"minio123"}}
  creationTimestamp: "2021-09-16T22:57:56Z"
  name: s3secret
  namespace: ramen-system
  resourceVersion: "42090"
  uid: 6f5c0289-4f5f-4933-8a18-bc780091ca4d
type: Opaque
```
Perhaps this is not an issue because only subjects with permission to read a `secret` can see it.  But in case it is, solutions may include a way to encode or encrypt the `last-applied-configuration` annotation or not store it at all.

**Comment by ShyamsundarR** [comment]
There is hardly any difference between the base64 (`data.`) encoded secrets and the ones in last-applied-configuration. Users/roles with permissions to read the secret can see the base64 blob anyway, which is only encoding and not encryption.

For further security of secrets, I think encrypted secrets or sealed secrets are the way forward.

**Comment by ShyamsundarR** [comment]
Closing this as dumping k8s secrets (by whoever has access to the same) would throw up the encoded (or otherwise) secret, hence not an issue.
