### ISSUE TITLE
Should DRPC actions be case sensitive matches, or can we take any mixed case actions?

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#290]
Currently the actions are matched exactly as per case `Failover` or `Relocate`. Should we move these to case-inseneitive matches? Does this break the API in anyway?

**Comment by raghavendrabhat** [comment]
One thing which makes me prefer the case insensitive is to avoid delay of operations such as failover due to human typos in DR Actions. However, I agree that it is important to consider if it will break the API.

**Comment by ShyamsundarR** [comment]
It remains case sensitive as of now.
