### ISSUE TITLE
SchedulingInterval is configure in multiple places

### ISSUE THREAD

**Issue by BenamarMk** [RamenDR/ramen#295]
SchedulingInterval is configured in the VolumeReplicationClass and DRPolicy. DRPC passes the SchedulingInterval to the VRG. A mismatch between the two values will cause the VRG instance to not make any forward progress.  The VRG logs the error, but the error is detected at the VRG level instead of close to where it is configured.

I propose to change DRPolity to either fail reconciliation if the SchedulingInterval is different from the VolumeReplicationClass' SchedulingInterval OR Use only the SchedulingInterval configured in the VolumeReplicatonClass

And while at it, change DRPC to add DRPolicy watcher so that if the DRPolicy CR is changed, the already created resources (like MW for VRG) get updated.

**Comment by ShyamsundarR** [comment]
With peerClasses and determination of VRClass having the right schedule, this check if moved closer to DRPolicy. Closing this issue.
