### ISSUE TITLE
Should VRG detect missing PVC storageClassName and match it to the default SC?

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#296]
With the [defaulting behaviour](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior) for PVCs, is it feasible that a PVC will not have the storageClassName field updated?

The text in the link states: `When a default StorageClass exists in a cluster and a user creates a PersistentVolumeClaim with storageClassName unspecified, the DefaultStorageClass admission controller automatically adds the storageClassName field pointing to the default storage class.`

If this ends up adding the storageClassName to the PVC spec, then we should be fine, if it is added to requests sent to various providers, then VRG would not find this value in the PVC spec that it inspects in the function `getStorageClass`.

This needs to be analyzed and confirmed, and if required we need to handle missing SC in the PVC and choose the default SC from the list of SCs to find the VRClass to use.

**Comment by raghavendrabhat** [comment]
Tested this scenario where the PVC definition did not have an explicit storageClass and a default storageClass was set in the kube cluster.

This works fine currently and VRG is able to get the storageClass of the PVC while creating VolRep resource using which it can select the appropriate VolumeReplicationClass and pass it  for VolRep creation.

Closing it.

**Comment by raghavendrabhat** [comment]
This is the PVC definition upon creation:

kubectl get pvc/mysql-pv-claim -n test --context cluster1 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"mysql-pv-claim","namespace":"test"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
    volumereplicationgroups.ramendr.openshift.io/vr-protected: protected
  creationTimestamp: "2021-09-28T15:57:44Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - volumereplicationgroups.ramendr.openshift.io/pvc-vr-protection
  labels:
    app: wordpress
  name: mysql-pv-claim
  namespace: test
  resourceVersion: "189966"
  uid: 68257ed1-779c-407f-bb8f-22cb9cc1d4c9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
  volumeMode: Filesystem
  volumeName: pvc-68257ed1-779c-407f-bb8f-22cb9cc1d4c9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound


And this is the YAML file of the pvc:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

**Comment by ShyamsundarR** [comment]
> kubectl.kubernetes.io/last-applied-configuration: | {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"labels":{"app":"wordpress"},"name":"mysql-pv-claim","namespace":"test"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}} pv.kubernetes.io/bind-completed: "yes" pv.kubernetes.io/bound-by-controller: "yes" volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com volumereplicationgroups.ramendr.openshift.io/vr-protected: protected creationTimestamp: "2021-09-28T15:57:44Z" finalizers:

>       spec:
>       storageClassName: rook-ceph-block

The last applied configuration and current spec shows the autofilled SC name, so we are good. Thanks @raghavendrabhat
