### ISSUE TITLE
optimizations for ensureNamespaceExistsOnManageCluster

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#298]
Based on #291 comments

Currently, `createVRGManifestWork` creates a ManagedClusterView to poll for the existence of a Namespace on a managed cluster. Since this call may be executed many times and ManagedClusterView is an expensive resource, add another check as a shortcut. 

Requirements: 
1. Check if the VRG ManifestWork exists first and if it was successfully created. If it was, then we can infer that the Namespace exists and the ManagedClusterView poll isn't required. If the VRG MW wasn't successfully created, then do the full ManagedClusterView check.
2. If the ManagedClusterView has successfully determined the existence or absence of a Namespace (meaning it has returned conditions and not just empty results), delete the ManagedClusterView since it's no longer needed.

**Comment by ShyamsundarR** [comment]
Closing as will not do.
