### ISSUE TITLE
after failover pvc and vr remain on "from" cluster with non-zero deletion timestamps and replication.storage.openshift.io finalizers

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#302]
configuration:
- hub: `hub`
- dr-clusters: `cluster1` `hub`

test:
1. busybox-sample application initial deployment on `cluster1`: succeeded
2. busybox-sample application failover to `hub`: succeeded
3. busybox-sample namespace delete on `cluster1`: failed because `pvc` and `vr` remain

I understand that a `vrg` creates child `vr`s and is also responsible for deleting them when it is deleted.  I wonder how the `vrg` was deleted but the `vr` was not.

logs:
[hub-operator-log.txt](https://github.com/RamenDR/ramen/files/7255550/hub-operator-log.txt)
[dr-cluster-operator-log-cluster1.txt](https://github.com/RamenDR/ramen/files/7255552/dr-cluster-operator-log-cluster1.txt)
[dr-cluster-operator-log-hub.txt](https://github.com/RamenDR/ramen/files/7255555/dr-cluster-operator-log-hub.txt)
hub objects:
[drpc.txt](https://github.com/RamenDR/ramen/files/7255556/drpc.txt)
[placementrule.txt](https://github.com/RamenDR/ramen/files/7255557/placementrule.txt)
dr-cluster objects:
[vrg-hub.txt](https://github.com/RamenDR/ramen/files/7255566/vrg-hub.txt)
[vr-cluster1.txt](https://github.com/RamenDR/ramen/files/7255560/vr-cluster1.txt)
[vr-hub.txt](https://github.com/RamenDR/ramen/files/7255561/vr-hub.txt)
[pvc-cluster1.txt](https://github.com/RamenDR/ramen/files/7255565/pvc-cluster1.txt)
[pvc-hub.txt](https://github.com/RamenDR/ramen/files/7255563/pvc-hub.txt)

**Comment by BenamarMk** [comment]
@hatfieldbrian the deletion of the VRG was correct.  I have seen this problem once and I investigated half part of it.  Basically, the way it works is that the DRPC deletes the VRG only after the VRG has reported that it has transitioned successfully to secondary.  The PVC was stuck in the terminating state because the VR finalizer was not removed by the VR (and not the VRG). The VRG deleted the VR and removed its VRG protection finalizer, but somehow the VR didn't finalize as expected.  A successful finalization will remove the pvc-protection from the PVC and they both terminate.  That didn't happen.  Can you please include the VR logs from cluster1?

**Comment by hatfieldbrian** [comment]
@BenamarMk I'm not sure which "vr" pod and container you want logs from, e.g.:
```
$ kubectl --context cluster1 get po -A
NAMESPACE                       NAME                                                   READY   STATUS      RESTARTS   AGE
busybox-sample                  busybox                                                1/1     Running     0          2m48s
kube-system                     coredns-74ff55c5b-4xqhv                                1/1     Running     0          6d20h
kube-system                     etcd-cluster1                                          1/1     Running     0          6d20h
kube-system                     kube-apiserver-cluster1                                1/1     Running     0          6d20h
kube-system                     kube-controller-manager-cluster1                       1/1     Running     0          6d20h
kube-system                     kube-proxy-8ptzx                                       1/1     Running     0          6d20h
kube-system                     kube-scheduler-cluster1                                1/1     Running     0          6d20h
kube-system                     storage-provisioner                                    1/1     Running     1          6d20h
minio                           minio-5f9c5bd8cd-5hskr                                 1/1     Running     0          6d20h
minio                           minio-setup-pk899                                      0/1     Completed   2          6d20h
multicluster-operators          multicluster-operators-subscription-5cb7dd8d68-5dflg   1/1     Running     0          6d20h
open-cluster-management-agent   klusterlet-addon-workmgr-fd8b8449b-dj7x6               1/1     Running     0          6d20h
open-cluster-management-agent   klusterlet-registration-agent-74c8c64f49-gjtp2         1/1     Running     0          6d20h
open-cluster-management-agent   klusterlet-work-agent-865f5949f8-r5rmt                 1/1     Running     0          6d20h
open-cluster-management         klusterlet-5c9d6c5476-rxf8x                            1/1     Running     0          6d20h
ramen-system                    ramen-dr-cluster-operator-bdd4cc95d-6mfv6              2/2     Running     0          8m54s
rook-ceph                       csi-cephfsplugin-9ntlv                                 3/3     Running     0          6d20h
rook-ceph                       csi-cephfsplugin-provisioner-85dd6fd578-vhrzp          6/6     Running     0          6d20h
rook-ceph                       csi-rbdplugin-gbcg7                                    3/3     Running     0          6d20h
rook-ceph                       csi-rbdplugin-provisioner-7f8f7d4bf4-l7jl9             8/8     Running     0          6d20h
rook-ceph                       rook-ceph-mgr-a-58c7b496dc-gz5p2                       1/1     Running     0          6d20h
rook-ceph                       rook-ceph-mon-a-d9cf84946-f9zq4                        1/1     Running     0          6d20h
rook-ceph                       rook-ceph-operator-5b94b79f5-fwkkl                     1/1     Running     0          6d20h
rook-ceph                       rook-ceph-osd-0-785bbc98c-xj4hz                        1/1     Running     0          6d20h
rook-ceph                       rook-ceph-osd-prepare-cluster1-zz5nz                   0/1     Completed   0          6d20h
rook-ceph                       rook-ceph-rbd-mirror-a-57d6f77987-hjf8j                1/1     Running     0          6d20h
rook-ceph                       rook-ceph-tools-6bc7c4f9fc-ddjn4                       1/1     Running     0          6d20h
```

**Comment by hatfieldbrian** [comment]
container image identifiers:
```sh
$ kubectl --context cluster1 describe po -nrook-ceph csi-rbdplugin-provisioner-7f8f7d4bf4-l7jl9

  volume-replication:
    Image:         quay.io/csiaddons/volumereplication-operator:latest
    Image ID:      docker-pullable://quay.io/csiaddons/volumereplication-operator@sha256:9c53ce8e3de3348dff5305fce4ff62eeaf02988855bb7bac246

csi-rbdplugin:
    Image:         quay.io/cephcsi/cephcsi:canary
    Image ID:      docker-pullable://quay.io/cephcsi/cephcsi@sha256:70e019ad56bd409f6ab46748a64de331ee1b87b3aedc68d50689dda3bede321a
```
cluster1 vr log:
```sh
$ kubectl --context cluster1 -nrook-ceph logs deploy/csi-rbdplugin-provisioner volume-replication
```
[vr-log-cluster1.txt](https://github.com/RamenDR/ramen/files/7261820/vr-log-cluster1.txt)

cluster1 vr log corresponding to its `deletionTimestamp: "2021-09-29T22:46:51Z"`:
```
```sh
{"level":"info","timestamp":"2021-09-29T22:41:59.270Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume is marked primary","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample"}
{"level":"info","timestamp":"2021-09-29T22:46:33.212Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume handle","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","VolumeHandleName":"0001-0009-rook-ceph-0000000000000002-741c9bcc-2176-11ec-99a4-0242ac11000a"}
{"level":"info","timestamp":"2021-09-29T22:46:33.988Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume is not ready to use","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample"}
{"level":"info","timestamp":"2021-09-29T22:46:49.009Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume handle","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","VolumeHandleName":"0001-0009-rook-ceph-0000000000000002-741c9bcc-2176-11ec-99a4-0242ac11000a"}
{"level":"info","timestamp":"2021-09-29T22:46:49.254Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume is marked secondary","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample"}
{"level":"info","timestamp":"2021-09-29T22:46:51.375Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume handle","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","VolumeHandleName":"0001-0009-rook-ceph-0000000000000002-741c9bcc-2176-11ec-99a4-0242ac11000a"}
{"level":"error","timestamp":"2021-09-29T22:46:51.520Z","logger":"controllers.VolumeReplication","caller":"controllers/volumereplication_controller.go:175","msg":"failed to disable volume replication","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
{"level":"error","timestamp":"2021-09-29T22:46:51.520Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"failed to disable replication","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
{"level":"error","timestamp":"2021-09-29T22:46:51.521Z","logger":"controller-runtime.manager.controller.volumereplication","caller":"controller/controller.go:253","msg":"Reconciler error","reconciler group":"replication.storage.openshift.io","reconciler kind":"VolumeReplication","name":"busybox-pvc","namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
{"level":"info","timestamp":"2021-09-29T22:46:51.526Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume handle","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","VolumeHandleName":"0001-0009-rook-ceph-0000000000000002-741c9bcc-2176-11ec-99a4-0242ac11000a"}
{"level":"error","timestamp":"2021-09-29T22:46:51.594Z","logger":"controllers.VolumeReplication","caller":"controllers/volumereplication_controller.go:175","msg":"failed to disable volume replication","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
{"level":"error","timestamp":"2021-09-29T22:46:51.595Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"failed to disable replication","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
{"level":"error","timestamp":"2021-09-29T22:46:51.595Z","logger":"controller-runtime.manager.controller.volumereplication","caller":"controller/controller.go:253","msg":"Reconciler error","reconciler group":"replication.storage.openshift.io","reconciler kind":"VolumeReplication","name":"busybox-pvc","namespace":"busybox-sample","error":"rpc error: code = InvalidArgument desc = secondary image status is up=true and state=unknown"}
```

**Comment by hatfieldbrian** [comment]
volume-replication finalize failure issue: https://github.com/csi-addons/volume-replication-operator/issues/119

**Comment by hatfieldbrian** [comment]
more logs:
[vr-log-hub.txt](https://github.com/RamenDR/ramen/files/7262066/vr-log-hub.txt)
[csi-rbdplugin-log-hub.txt](https://github.com/RamenDR/ramen/files/7262068/csi-rbdplugin-log-hub.txt)
[csi-rbdplugin-log-cluster1.txt](https://github.com/RamenDR/ramen/files/7262070/csi-rbdplugin-log-cluster1.txt)

**Comment by hatfieldbrian** [comment]
Updated cephcsi from:
`quay.io/cephcsi/cephcsi@sha256:70e019ad56bd409f6ab46748a64de331ee1b87b3aedc68d50689dda3bede321a` to
`quay.io/cephcsi/cephcsi@sha256:81148b52ae3b78efbd029615fadcc50dd02a9e628b53683de2406794911a8ec4` and restarted `csi-rbdplugin-provisioner` deployment on each cluster, but unfinalized `vr` and `pvc` issue remains.

**Comment by hatfieldbrian** [comment]
Updated `volume-replication` from
`quay.io/csiaddons/volumereplication-operator@sha256:9c53ce8e3de3348dff5305fce4ff62eeaf02988855bb7bac246` to
`quay.io/csiaddons/volumereplication-operator@sha256:f6659107601fdb55835855cfd59de66e311972894efbf60ac6e136fb90a13c64` and restarted `csi-rbdplugin-provisioner` deployment on each cluster, and unfinalized `vr` and `pvc` due to `replication.storage.openshift.io` finalizer issue is not present!
However, `pvc` and `vrg` remain due to `volumereplicationgroups.ramendr.openshift.io/pvc-vr-protection` and `volumereplicationgroups.ramendr.openshift.io/vrg-protection` finalizers respectively.

**Comment by hatfieldbrian** [comment]
End-to-end test now checks for pvc and vr resources to be removed on "from" cluster for both failover and relocate and now seem to be reliably removed.

**Comment by VphDreamer** [comment]
@hatfieldbrian @BenamarMk Hello, so I'm trying to do some tests using Ramen on Openshift, The failover and relocation worked fine, but, now, strangely, it does not work anymore, after a failover, the PVC is stuck in terminating status in the "from" cluster, neither the VR nor the VRG is deleted. so I cannot relocate.

**Comment by BenamarMk** [comment]
So when the failover succeeds, DRPC will try to clean up the '*from*'
cluster.  In doing so, it will first update the Manifestwork (on the
hub) for the '*from*' cluster. The VRG is changed to Secondary.  That
update must be applied to the '*from*' cluster. So, you will need to make
sure the VRG in the '*from*' cluster spec.ReplicationState == Secondary.
If it is still saying Primary, then the Manifestwork hasn't been applied on
the '*from*' cluster. The status of the Manifestwork will give you a hint.

If the .spec.ReplicationState is secondary, then the VR is trying to demote
the image to secondary and resyncs with the new primary.  Nothing will
happen until that step is complete.  Once that step is complete, then the
VRG status will be updated to reflect the ReplicationState (secondary).
After that, the DRPC will delete the VRG on the '*from*' cluster.  Deleting
the VRG will first delete the VR, the finalizers will be removed from the
PVC and then the PVC goes away.  That's what happens in a nutshell.

**Comment by VphDreamer** [comment]
@BenamarMk here is the VRG in the from cluster, the spec.ReplicationState is set to secondary, but, in status, we can see a primary:
```
apiVersion: ramendr.openshift.io/v1alpha1
kind: VolumeReplicationGroup
metadata:
  resourceVersion: '36810651'
  name: busybox-drpc
  uid: 8649bf70-9a88-46d0-a57a-8d03e628ed34
  creationTimestamp: '2022-07-21T07:28:49Z'
  generation: 2
  managedFields:
    - apiVersion: ramendr.openshift.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"volumereplicationgroups.ramendr.openshift.io/vrg-protection"': {}
      manager: manager
      operation: Update
      time: '2022-07-21T07:28:49Z'
    - apiVersion: ramendr.openshift.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:lastUpdateTime': {}
          'f:observedGeneration': {}
          'f:protectedPVCs': {}
          'f:state': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2022-07-21T07:29:48Z'
    - apiVersion: ramendr.openshift.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:ownerReferences':
            .: {}
            'k:{"uid":"7b45e3b3-7d17-4a72-b693-9847b5f43e0c"}': {}
        'f:spec':
          .: {}
          'f:action': {}
          'f:async':
            .: {}
            'f:mode': {}
            'f:replicationClassSelector': {}
            'f:schedulingInterval': {}
          'f:pvcSelector':
            .: {}
            'f:matchLabels':
              .: {}
              'f:appname': {}
          'f:replicationState': {}
          'f:s3Profiles': {}
          'f:sync':
            .: {}
            'f:mode': {}
      manager: work
      operation: Update
      time: '2022-07-21T07:38:18Z'
  namespace: busybox-sample
  ownerReferences:
    - apiVersion: work.open-cluster-management.io/v1
      kind: AppliedManifestWork
      name: >-
        5c41238f1c4c5b9b686bdb1d16b10dab6e9dffed3808268a14c4062954601b04-busybox-drpc-busybox-sample-vrg-mw
      uid: 7b45e3b3-7d17-4a72-b693-9847b5f43e0c
  finalizers:
    - volumereplicationgroups.ramendr.openshift.io/vrg-protection
spec:
  action: Failover
  async:
    mode: Enabled
    replicationClassSelector: {}
    schedulingInterval: 5m
  pvcSelector:
    matchLabels:
      appname: busybox
  replicationState: secondary
  s3Profiles:
    - s3profile-dr-primary-ocs-storagecluster
    - s3profile-dr-secondary-ocs-storagecluster
  sync:
    mode: Disabled
status:
  conditions:
    - lastTransitionTime: '2022-07-21T07:38:18Z'
      message: VolumeReplicationGroup is progressing
      observedGeneration: 2
      reason: Progressing
      status: 'False'
      type: DataReady
    - lastTransitionTime: '2022-07-21T07:38:18Z'
      message: VolumeReplicationGroup is replicating
      observedGeneration: 2
      reason: Replicating
      status: 'False'
      type: DataProtected
    - lastTransitionTime: '2022-07-21T07:29:48Z'
      message: Restored PV cluster data
      observedGeneration: 1
      reason: Restored
      status: 'True'
      type: ClusterDataReady
    - lastTransitionTime: '2022-07-21T07:38:18Z'
      message: Cluster data of all PVs are protected
      observedGeneration: 2
      reason: Uploaded
      status: 'True'
      type: ClusterDataProtected
  lastUpdateTime: '2022-07-21T07:38:19Z'
  observedGeneration: 2
  protectedPVCs:
    - conditions:
        - lastTransitionTime: '2022-07-21T07:38:18Z'
          message: Updated VolumeReplication resource for PVC
          observedGeneration: 2
          reason: Progressing
          status: 'False'
          type: DataReady
        - lastTransitionTime: '2022-07-21T07:29:49Z'
          message: >-
            Done uploading PV cluster data to 2 of 2 S3 profile(s):
            [s3profile-dr-primary-ocs-storagecluster
            s3profile-dr-secondary-ocs-storagecluster]
          observedGeneration: 1
          reason: Uploaded
          status: 'True'
          type: ClusterDataProtected
        - lastTransitionTime: '2022-07-21T07:29:49Z'
          message: PVC in the VolumeReplicationGroup is ready for use
          observedGeneration: 1
          reason: Replicating
          status: 'False'
          type: DataProtected
      name: busybox-pvc
  state: Primary
```

**Comment by VphDreamer** [comment]
and this is the VR :
```
apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeReplication
metadata:
  resourceVersion: '36896180'
  name: busybox-pvc
  uid: 72d2620b-8085-4152-97b3-bc3751aebb1f
  creationTimestamp: '2022-07-21T07:29:48Z'
  generation: 2
  namespace: busybox-sample
  ownerReferences:
    - apiVersion: ramendr.openshift.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: VolumeReplicationGroup
      name: busybox-drpc
      uid: 8649bf70-9a88-46d0-a57a-8d03e628ed34
  finalizers:
    - replication.storage.openshift.io
spec:
  dataSource:
    apiGroup: ''
    kind: PersistentVolumeClaim
    name: busybox-pvc
  replicationHandle: ''
  replicationState: secondary
  volumeReplicationClass: rbd-volumereplicationclass-1625360775
status:
  conditions:
    - lastTransitionTime: '2022-07-21T07:39:27Z'
      message: ''
      observedGeneration: 2
      reason: Demoted
      status: 'True'
      type: Completed
    - lastTransitionTime: '2022-07-21T07:38:20Z'
      message: ''
      observedGeneration: 2
      reason: VolumeDegraded
      status: 'True'
      type: Degraded
    - lastTransitionTime: '2022-07-21T08:39:23Z'
      message: ''
      observedGeneration: 2
      reason: ResyncTriggered
      status: 'True'
      type: Resyncing
  lastCompletionTime: '2022-07-21T07:29:54Z'
  lastStartTime: '2022-07-21T07:29:48Z'
  message: volume is degraded
  observedGeneration: 2
  state: Secondary
```

**Comment by BenamarMk** [comment]
So the VR looks like is resyncing
```

 lastTransitionTime: '2022-07-21T08:39:23Z'
      message: ''
      observedGeneration: 2
      reason: ResyncTriggered
      *status: 'True'*
      type: Resyncing

```

**Comment by BenamarMk** [comment]
I am not sure what other things are preventing the resync to complete.  We
need to look at the logs and run a few RBD commands in order to determine
the cause.

**Comment by VphDreamer** [comment]
@BenamarMk what are the logs that I need to check ?

**Comment by BenamarMk** [comment]
You can always start by looking at the VR log, which is found in one of the
*csi-rbdplugin-provisioner* instances
oc logs -n openshift-storage  csi-rbdplugin-provisioner-85559d89d8-fdbpf -c
volume-replication

replace the namespace and the pod name with the correct ones.

**Comment by VphDreamer** [comment]
is this can be helpful:
`{"level":"info","timestamp":"2022-07-21T09:32:07.254Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume is not ready to use, requeuing for resync","Request.Name":"mongodb","Request.Namespace":"letschat-rhacm"}            {"level":"info","timestamp":"2022-07-21T09:32:16.258Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume handle","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample","VolumeHandleName":"0001-0011-openshift-storage-0000000000000001-e645c90a-08c6-11ed-9975-0a580a870010"}                             {"level":"info","timestamp":"2022-07-21T09:32:16.478Z","logger":"controllers.VolumeReplication","caller":"controller/controller.go:298","msg":"volume is not ready to use, requeuing for resync","Request.Name":"busybox-pvc","Request.Namespace":"busybox-sample"} `

**Comment by BenamarMk** [comment]
Most likely the issue is some kind of rbd split-brain error on that image.
We definitely can't debug it through emails.  We should probably have
access to the cluster or at least collect must-gather.
In the meantime, I'll be interested to see the output of `rbd mirror image
status` for that image.

**Comment by VphDreamer** [comment]
I find that the status of the image is correct, it "up+replaying" in the "from" cluster and primary in the failover cluster.
One thing I tried is that I deleted the VRG manually and then the "from" cluster is cleaned (VRG, VR and PVC are deleted), and then I managed to relocate. Personally, I think for some reason, it's just that the VRG that is not updated.

**Comment by BenamarMk** [comment]
Well, the VRG gets deleted when its status state is updated to Secondary.
That wasn't the case and you force deletion.  Anyway, there was a glitch
somewhere.  The mismatch state between the VRG and VR didn't make sense to
me.  If it happens again, we would be interested in digging further.  BTW,
what version is this?

**Comment by VphDreamer** [comment]
I'm working on Openshift, so, I don't know exactly the version of ramen, but, these are the versions of Openshift and the installed operators:

> Openshift: 4.10.20
> ACM : 2.0.5 
> ODF Multicluster Orchestrator: 4.10.5
> Openshift DR Hub Operator: 4.10.5
> Openshift DR Cluster Operator: 4.10.5 

I don't know how can I help to debug this, the clusters are provisioned on-premises, they are not accessible to public. and I'm not yet sure how to reproduce the issue.

**Comment by VphDreamer** [comment]
@BenamarMk So, If I do understand, having the VR status as secondary is not sufficient so that VRG status will be set to secondary , other checks are done right ? https://github.com/RamenDR/ramen/blob/26b5feac8a8a1eeea94226a2091b33faaa977814/controllers/vrg_volrep.go#L1110
l need to have the *Rysincing* set to false, is that right? does this depends on the RBD layer ?

**Comment by BenamarMk** [comment]
That's correct. VR needs to mark the volume as secondary and resyncs
successfully before the VRG .status.state is updated. Only after all VRs
have been moved to secondary successfully, the VRG .status.State is updated
to secondary.  From the VR output above, the condition shows that the
volume was degraded.
Can you attach the Ramen log file from the 'from' cluster?

**Comment by VphDreamer** [comment]
[logs_ramen.log](https://github.com/RamenDR/ramen/files/9162240/logs_ramen.log)

**Comment by VphDreamer** [comment]
@BenamarMk, So I tried to force the image resyncing with the following command:
`rbd mirror image resync csi-vol-84d312cc-08ee-11ed-9c73-0a580a850422`
Then I noticed these changes in the VR status, It tried to Resync but failed and then after it returns to its previous status.

```
status:
  conditions:
    - lastTransitionTime: '2022-07-21T20:01:30Z'
      message: ''
      observedGeneration: 2
      reason: FailedToResync
      status: 'False'
      type: Completed
    - lastTransitionTime: '2022-07-21T12:22:47Z'
      message: ''
      observedGeneration: 2
      reason: Error
      status: 'True'
      type: Degraded
    - lastTransitionTime: '2022-07-21T20:01:30Z'
      message: ''
      observedGeneration: 2
      reason: FailedToResync
      status: 'False'
      type: Resyncing
  lastCompletionTime: '2022-07-21T12:13:28Z'
  lastStartTime: '2022-07-21T12:13:24Z'
  message: 'failed to get local status: rbd: ret=-2, No such file or directory'
  observedGeneration: 2
  state: Secondary
```

**Comment by VphDreamer** [comment]
I want to indicate that I now think it's not a Ramen bug, it may be more related to my environment, something maybe changed.
Say that I have two clusters "east" and "west". In a scenario where the app is deployed originally in the cluster "east", I manage to failover to cluster "west", but, the cluster "east" is not well cleaned up. However, if I tried to deploy originally the app in the cluster "west", the failover, the cleanup, the relocating, all work fine. So, guess in my cluster "east", I may accidently deleted or changed something that triggered this behavior.
