### ISSUE TITLE
double quote each string literal unless its backslash escapes should not be interpreted

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#317]
There are multiple ways to quote string literals:
- backticks, which result in no interpretation, and
- double quotes, which result in interpretation of backslash escapes

Some team members prefer double quotes by default even if interpretation is not needed, and presumably backticks only if backslash escapes should not be interpreted:
https://github.com/RamenDR/ramen/pull/310/files#r731789014

This issue tracks changing the code, particularly changes made in pull request #310, to match team members' preferences.

**Comment by ShyamsundarR** [comment]
This is dealt with, closing.
