### ISSUE TITLE
volume management is limited to a namespace and requires permission to label volume claims

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#343]
# Background
A volume replication group's protection/recovery/relocation unit is a set of persistent volume claims within a single namespace having a user-specified label.  This allows a user/application developer to decide when to recover or relocate a group of volumes by modifying a single volume replication group object's spec.

# Problem use case
A storage administrator needs to protect/recover/relocate a group of persistent volumes that may span namespaces and lacks permission to label all their claims.

# Solution approaches
1. Provide ability to select volumes based on their storage class
  pros:
    -  a cluster-scoped volume replication group could manage an entire cluster
2. Provide ability to select all volumes in a namespace
  cons:
    - may include some volumes that need not be protected
    - a volume replication group must be managed for each namespace
3. Provide a cluster-level way to manage a set of volume replication groups spanning namespaces combined with solutions 1 and/or 2 for selecting volumes

**Comment by ShyamsundarR** [comment]
With discovered workload support for multiple namespaces, this feature is partly satisfied. No requests for non-label based PVC filtering in or across namespaces ave been made, and that is not fixed. Closing this issue for now, to be reopened if such schemes are required.
