### ISSUE TITLE
Specify S3 store region in VRG input

### ISSUE THREAD

**Issue by vdeenadh** [RamenDR/ramen#36]
When using an S3 store like velero, the concept of region doesn't apply and default's to us-east-1.  However, if we need to support a cloud based S3 store, yes, we may need take region as an input, among other TBD parameters. 

_Originally posted by @vdeenadh in https://github.com/RamenDR/ramen/pull/33#discussion_r605384004_

**Comment by ShyamsundarR** [comment]
These are technically closed, and latest work to move these out of DRPC is being done in #117
