### ISSUE TITLE
minikube-rook-setup.sh: `virsh domblkinfo` failed to get domain

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#414]
Initially I got an error that osd0-cluster1 already exist. So I manually deleted the image. After that when I ran the script I found this error. 
```sh
+ virsh vol-info --pool minikube osd0-cluster1
error: failed to get vol 'osd0-cluster1'
error: Storage volume not found: no storage vol with matching path 'osd0-cluster1'

+ virsh vol-create-as --pool minikube --name osd0-cluster1 --capacity 32G --format qcow2
Vol osd0-cluster1 created

+ virsh domblkinfo --domain cluster1 --device vdb
error: failed to get domain 'cluster1'

+ sudo virsh attach-disk --domain cluster1 --source /home/jmishra-vm/.minikube/images/osd0-cluster1 --target vdb --persistent --driver qemu --subdriver qcow2 --targetbus virtio
error: Failed to attach disk
error: Requested operation is not valid: target vdb already exists
```
_Originally posted by @jmishrarh in https://github.com/RamenDR/ramen/issues/407#issuecomment-1081655027_

**Comment by Madhu-1** [comment]
>minikube start -h |grep -i disk
      --disk-size='20000mb': Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g).
      --extra-disks=0: Number of extra disks created and attached to the minikube VM (currently only implemented for hyperkit and kvm2 drivers)

minikube already supports creating disks when creating the cluster. we can make use of it?

**Comment by hatfieldbrian** [comment]
@jmishrarh I presume minikube `cluster1` was deleted but volume `od0-cluster1` was not though it should have been:
https://github.com/RamenDR/ramen/blob/e00745d0f13e1bf5a9fae4d9e5e87431d7e3889d/hack/minikube-rook-setup.sh#L71-L76  

I wonder why domain `cluster1` was inaccessible by a block device query, but then accessible to determine the same device it just attempted to query already existed:

> ```sh
> + virsh domblkinfo --domain cluster1 --device vdb
> error: failed to get domain 'cluster1'
> 
> + sudo virsh attach-disk --domain cluster1 --source /home/jmishra-vm/.minikube/images/osd0-cluster1 --target vdb --persistent --driver qemu --subdriver qcow2 --targetbus virtio
> error: Failed to attach disk
> error: Requested operation is not valid: target vdb already exists
> ```

Perhaps the first command lacked permission and the second had it as it was run as root?

@jmishrarh will you please try running the part that is failing again by issuing following command:
```sh
hack/ocm-minikube-ramen.sh rook_ceph_deploy_spoke\ cluster1
```

@Madhu-1 
> minikube already supports creating disks when creating the cluster. we can make use of it?

e2e scripts are already using some minikube-isms, e.g. image load, image registry addon, so what's one more?  @ShyamsundarR

**Comment by jmishrarh** [comment]
hack/ocm-minikube-ramen.sh rook_ceph_deploy_spoke\ cluster1

+ virsh vol-info --pool minikube osd0-cluster1
Name:           osd0-cluster1
Type:           file
Capacity:       32.00 GiB
Allocation:     196.00 KiB

+ virsh domblkinfo --domain cluster1 --device vdb
error: failed to get domain 'cluster1'

+ sudo virsh attach-disk --domain cluster1 --source /home/jmishra-vm/.minikube/images/osd0-cluster1 --target vdb --persistent --driver qemu --subdriver qcow2 --targetbus virtio
error: Failed to attach disk
error: Requested operation is not valid: target vdb already exists

**Comment by hatfieldbrian** [comment]
@jmishrah Thanks for re-running the `virsh domblkinfo --domain cluster1 --device vdb` command.  In effort to debug this "failed to get domain" error, will you please issue the following commands:
```sh
virsh list --all
virsh dominfo cluster1
virsh domcontrol cluster1
virsh domblklist cluster1
virsh domblkerror cluster1
```
For example:
```sh
$ virsh list --all
 Id    Name                           State
----------------------------------------------------
 147   cluster2                       running
 148   hub                            running
 149   cluster1                       running
$ virsh dominfo cluster1
Id:             149
Name:           cluster1
UUID:           15f0cb3f-523c-4778-94d9-64257a047cd0
OS Type:        hvm
State:          running
CPU(s):         2
CPU time:       611427.5s
Max memory:     6144000 KiB
Used memory:    6144000 KiB
Persistent:     yes
Autostart:      disable
Managed save:   no
Security model: apparmor
Security DOI:   0
Security label: libvirt-15f0cb3f-523c-4778-94d9-64257a047cd0 (enforcing)
$ virsh domcontrol cluster1
ok
$ virsh domblklist cluster1
Target     Source
------------------------------------------------
hdc        /home/bhatfiel/.minikube/machines/cluster1/boot2docker.iso
hda        /home/bhatfiel/.minikube/machines/cluster1/cluster1.rawdisk
vdb        /home/bhatfiel/.minikube/images/osd0-cluster1
$ virsh domblkerror cluster1
No errors found
```
Also, it may help to replace `cluster1` with `hub` in the commands to see how the outputs vary.  Thank you.

**Comment by ShyamsundarR** [comment]
Stale, we have moved to drenv.
