### ISSUE TITLE
Add supported arch to CSV bundles

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#510]
See [this](https://olm.operatorframework.io/docs/advanced-tasks/ship-operator-supporting-multiarch/)

We need to add the following labels to out base CSV:

```
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
```

CSVs:
- [hub](https://github.com/RamenDR/ramen/blob/main/config/hub/manifests/bases/ramen_hub.clusterserviceversion.yaml)
- [dr-cluster](https://github.com/RamenDR/ramen/blob/main/config/dr-cluster/manifests/bases/ramen_dr_cluster.clusterserviceversion.yaml)

As an aside this also helps downstream builds add a label to denote the full CSV version in the bundle.

**Comment by rakeshgm** [comment]
I believe the fix is in this PR https://github.com/RamenDR/ramen/pull/824
