### ISSUE TITLE
order of subscription deletion and marking VolumeReplicationGroup Secondary

### ISSUE THREAD

**Issue by raghavendrabhat** [RamenDR/ramen#53]
When a kubernetes system is down in a regional DR setup, the applications running there which are disaster protected are failed over to the peer kubernetes system. Now, when the 1st kubernetes system which was the primary and was running the application workload comes up, following 2 actions happen from ocm(open-cluster-management) hub.

1) Deletion of the subscription (or application) present in the managed cluster that just came up
2) Marking the VolumeReplicationGroup from that managed cluster as secondary (as the application has already failed over to
    the peer cluster).

Now, if (2) happens 1st before step (1), then all the VolumeReplication resources created by VolumeReplicationGroup resource in that managed cluster would be marked as secondary, which in turn would go down and mark the associated storage objects
as the secondary objects for the async replication relationship. Then if step (1) happens, then the subscription deletion would happen leading to the deletion of the subcscription deployments, pvcs etc.  The underlying storage would have been appropriately marked secondary before the subscription deletion.

However if (1) happens before (2), then before the underlying storage objects can be marked secondary, the pvcs associated with the subscription would have been deleted, thus deleting the underlying VolumeReplication resource. But, the storage objects on which the pvcs are based would not be marked secondary for the async replication relationship. And once pvcs are deleted, when step (2) happens, there would not be a way for VolumeReplicationGroup controller to mark the storage objects as secondary as the pvcs are not there and the associated VolumeReplication resources have been deleted as well.

**Comment by ShyamsundarR** [comment]
@raghavendrabhat with the added PVC finalizer this should not occur, right? Can you confirm once, thanks.

**Comment by raghavendrabhat** [comment]
ACK. This understanding is correct. i.e. with the finalizers put on PVC by VRG, if (1) happens first, then the pvcs would not go away due to the finalizers (hence VolumeReplication resources would still be present). Later when VRG is marked secondary, it would go ahead and mark the underlying VolumeReplication resources secondary allowing the underlying storage objects to be marked as secondary as well.

**Comment by ShyamsundarR** [comment]
Closing this as it is handled by the finalizers.
