### ISSUE TITLE
Applying Persistent Volume resource to failover cluster

### ISSUE THREAD

**Issue by raghavendrabhat** [RamenDR/ramen#59]
Currently, to be able to failover the application to a Disaster Protected peer cluster, VolumeReplicationGroup uploads the PV metadata to an object store. Later, at the time of the failover those PV metadata can be applied to the failover cluster. Though initially it was supposed to be VolumeReplicationGroup resource on the peer cluster which should be pulling and PV metadata and applying them, currently it is ApplicationVolumeReplication (AVR) controller which applies the PV metadata manifest on the appropriate managed cluster to which failover is happening. 

One of the major reasons for choosing ApplicationVolumeReplication to do this instead of VolumeReplicationGroup on  the managed cluster was, the unavailability of mechanisms to check from the hub whether the VolumeReplicationGroup that has been applied to the appropriate managed cluster (i.e. failover cluster to be precise) is in a ready state for subsequent deployment of the application.

With PR https://github.com/RamenDR/ramen/pull/57 there is a way to get the status of the VolumeReplicationGroup resource from the managed cluster. So, with this, would it be better for VolumeReplicationGroup from the failover cluster to pull down the PV metadata from the object store and apply them locally? ApplicationVolumeReplication (AVR) can check the status of VolumeReplicationGroup that has been applied to the failover cluster to decide whether to go ahead with deployment of application or not (depending upon whether VolumeReplicationGroup is ready or not).

**Comment by ShyamsundarR** [comment]
I would go with the current pattern of AVR applying the PV manifest for failback as well. There is PV garbage collection that needs to be done by AVR as well.

- Failback is coordinated by AVR, so we need PVs restored before PVCs are created on the system
    - So if VRG has to restore PVs in a failback situation, it needs to know it is failback (or some toggle to restore PVs and not bother with PVCs at all)
    - AVR has to create VRG in this format, and then only shift the placement to the preferred (failback) cluster
    - Instead of the above, as AVR restores PVCs for failover, it can restore it for failback before changing the placement

- PV MW garbage collection
    - As AVR creates the PV ManifestWork, these need to be deleted when a cluster is no longer holding the VRG
    - This needs to be done as otherwise OCM will keep maintaining the MW on the managed cluster and keep recreating the PVs
    - This has to be done post VRG deletion, and hence cleaning up any PV MWs on the cluster
        - This is so that we first mark the PV as reclaim and then later delete the PV MW

Overall, for the coordination steps in between changing placement (and hence creating PVCs on a cluster) and having PVs on the cluster ready to bind, AVR doing the same would be appropriate and easier to reason with.

**Comment by ShyamsundarR** [comment]
> I would go with the current pattern of AVR applying the PV manifest for failback as well. There is PV garbage collection that needs to be done by AVR as well.

We are changing VRG to restore (and also gaarbage collect) PVs from the S3 stores.

> 
>     * Failback is coordinated by AVR, so we need PVs restored before PVCs are created on the system
>       
>       * So if VRG has to restore PVs in a failback situation, it needs to know it is failback (or some toggle to restore PVs and not bother with PVCs at all)
>       * AVR has to create VRG in this format, and then only shift the placement to the preferred (failback) cluster

A basic condition as per the above is what DRPC does in #197 

>       * Instead of the above, as AVR restores PVCs for failover, it can restore it for failback before changing the placement
> 
>     * PV MW garbage collection
>       
>       * As AVR creates the PV ManifestWork, these need to be deleted when a cluster is no longer holding the VRG
>       * This needs to be done as otherwise OCM will keep maintaining the MW on the managed cluster and keep recreating the PVs
>       * This has to be done post VRG deletion, and hence cleaning up any PV MWs on the cluster

As MW is no longer in play, as in #197 garbage collection is handled by VRG directly.

>         
>         * This is so that we first mark the PV as reclaim and then later delete the PV MW
> 
> 
> Overall, for the coordination steps in between changing placement (and hence creating PVCs on a cluster) and having PVs on the cluster ready to bind, AVR doing the same would be appropriate and easier to reason with.
