### ISSUE TITLE
Add option to skip self tests when starting test enviroment

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#594]
When starting test environment we run several self tests:

    $ drenv start regional-dr.yaml
    ...
    2022-11-08 20:41:57,928 INFO    [env] Starting klusterlet/test
    2022-11-08 20:42:29,305 INFO    [env] klusterlet/test completed in 31.38 seconds
    ...
    2022-11-08 20:45:10,047 INFO    [env] Starting rbd-mirror/test
    2022-11-08 20:45:24,556 INFO    [env] rbd-mirror/test completed in 14.51 seconds
    2022-11-08 20:45:24,556 INFO    [env] Started in 593.83 seconds

The tests are very useful for developing and debugging the test
environment, but are not needed when we create the test environment
for testing or developing ramen.

Plan
- Skip tests in `drenv start`
- Add --selftest to enable the tests when needed
- Or provide a `drevnv selftest` command to run all tests on a started environment

**Comment by ShyamsundarR** [comment]
The self tests are to ensure the environment is sane. We have had issues in the past with mirroring not setup right or functioning correctly and as a result catching these early helps, rather than later via the ramen stack.

The self tests themselves are short (mostly) and help avoid unwanted troubleshooting of the environment assuming e2e failures in the same.

**Comment by nirs** [comment]
I agree that the self tests are important, and we want to add more tests. But we don't
want to run them every time you start the environment. Running or not running the tests
should be configurable.

For example in CI environment running tests for 60 minutes, spending 5 minutes on verifying
the environment may be ok. But if you start the environment during development multiple time
for running 5 minutes test, it does not make sense to double the time for self tests when
nothing was changed.

We can also have separate CI job running every day to make sure the current environment
works, so we don't have to verify it every time we run the tests.

The most important thing it to make the system flexible so we can use it in the best way.

What I thinking about is:

- Unify the arguments of the tests and start scripts
- Remove the /start and /test parts from the script, the yaml will only specify the component name
- During start, run only `{component}/start`
- If we add a --selftest flag, run also `{component}/test`
- If we add a `test` command, it will run all `{component}/test` scripts

**Comment by ShyamsundarR** [comment]
> I agree that the self tests are important, and we want to add more tests. But we don't want to run them every time you start the environment. Running or not running the tests should be configurable.

When you say `start` the environment you mean setup from scratch, or restart an environment that is already setup?

The scheme to add `--selftest` as an option is useful, so that the base YAML file for setup is not modified, rather parts of it executed or not. Should we consider `--disableselftest` instead to avoid any surprises even for local dev environments?

**Comment by nirs** [comment]
> When you say `start` the environment you mean setup from scratch, or restart an environment that is already setup?

We don't have different semantics for "start" or "create". All the code is idempotent and creating from scratch, starting stopped environment or restarting after partial failure are all the same.

> The scheme to add `--selftest` as an option is useful, so that the base YAML file for setup is not modified, rather parts of it executed or not. Should we consider `--disableselftest` instead to avoid any surprises even for local dev environments?

We can add --skip-tests or --no-tests, but this will make life harder for developers that are
likely to recreate an environment a lot when nothing has changed.

Cases when you want to run the tests:
- Changing drenv or the scripts - rare
- Testing that current dependencies did not break the setup - periodic CI job is best for this
- Aborting early in long CI tests
- Verifying a new environment before using it for long time

Cases when you don't want to run the tests:
- Creating/starting the environment for development - common

So I think that we should have:
- `start --verify` flag - don't skip */test scripts
- `verify` command - run all */test scripts

A simple implementation can assume that "*/test" is a test script and "*/start" is a start script, without unifying the arguments.

**Comment by nirs** [comment]
Self tests were proven useful so far, detecting recent regressions in our dependencies.

So I think we should go with the safe way of running the tests by default, and adding
an otion to skip them like:

    drenv start --skip-tests

To make it possible to start the enviroment faster when it is needed.

**Comment by nirs** [comment]
@Shwetha-Acharya is working on this.
