### ISSUE TITLE
Developer document

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#607]
In [CONTRIBUTING.md](https://github.com/RamenDR/ramen/blob/main/CONTRIBUTING.md) we have:

- Read the [install](docs/install.md) guide for build and deploy instructions
  - It is impossible to build and deploy based on this page. I think now that we have a working test environment we can document how to use it.

- Play with the project, submit bugs, submit patches!
  - It is impossible to play with the project when you cannot install it, but even if you could install it, we need instructions how to run common flows, maybe in the form of example scripts creating applications protected by ramen and using ramen to relocate or failover.

- Make sure all [tests](docs/testing.md) pass, and add any new [tests](docs/testing.md) as appropriate.
  - Current info is not very useful, we need to point to relevant e2e tests showing the main flows, and instruction how to run the tests and how to add new tests.

I think we need a dedicated document for developers, that can be used by a new contributor to build, deploy, run existing system tests, and play with the system. Something like [minikube start](https://minikube.sigs.k8s.io/docs/start/).

**Comment by ShyamsundarR** [comment]
We have been lax in documentation and also have that as one of the items to complete before the first release of any sort. If you are starting any documentation, let us please look at a broader TOC initially and then start on individual documents.
