### ISSUE TITLE
Protect against multiple AVR resources referencing the same user PlacementRule

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#62]
It is possible that a user may create more than one AVR resource that points to a single user PlacementRule. This would cause reconciliation of the 2 instances to incorrectly manage the user PlacementRule.

Although this is a user error, the AVR reconciler needs to protect against such misconfiguration.

One scheme could be to add an annotation on ownership to the user PlacementRule with a unique value (UID of AVR resource that firsts owns the PlacementRule), and check if this is the same across reconciliations and error out for duplicate AVR resources that point to the same PlacementRule.

**Comment by BenamarMk** [comment]
Veera and I thought about this couple of weeks ago.  We decided at that time that would be a user error and we didn’t want to solve it at that point.  But annotation is definitely one way of doing it.

**Comment by BenamarMk** [comment]
This is fixed
