### ISSUE TITLE
last sync time information

### ISSUE THREAD

**Issue by raghavendrabhat** [RamenDR/ramen#66]
Currently there is no information about for each protected PVC (or VolumeReplicationGroup as a whole) when is the last time data from the underlying storage volume was replicated to the regional peer cluster. That information might help in understanding how much the peer cluster may be lagging from the primary cluster where the application is running. 

For this, VolumeReplicationGroup mainly has to depend on the underlying VolumeReplication resource. However, as of now, there is no such information available from VolumeReplication resource to indicate the last time when a data sync happened between the primay cluster and its peer. When VolumeReplication resource makes such information available, VolumeReplicationGroup can consume it.

**Comment by ShyamsundarR** [comment]
Closing this issue in favor of #181
