### ISSUE TITLE
ramen_last_sync_timestamp_seconds metric

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#706]
ramen_last_sync_timestamp_seconds
  - Type: Gauge
    - Can go down in a resync case, or where it is not yet established post relocate
  - Labels:
    - resource_type: [drpc|vrg|volume(pvc)]
      - future: will there be a volumegroup type?
      - Label based on resource reporting the metric, and for the resource it is reporting it for
    - name: Name of the resource
    - namespace: Namespace of the resource
    - schedule_interval: [<scheduleIntervalInSeconds>|...]
  - Use-case:
    - Historical data on RPO breaches
    - Can plot hot/cold periods to plan for actions like relocate
    - Can alert when resource is off target from a schedule_interval perspective
  - Code mechanics:
    - last[Group]SyncTime
      - Updated when a VR reports the same causing a reconcile of VRG (and hence DRPC)
    - Report each time status is updated for a resource
      - Or just each time anyway, as it is a local cache, and the collector will pick up the current value, so an in memory update for all practical purposes
    - When an action is in progress, this reporting has to be stopped/stalled to the last known time
      - Technically the lastSyncTime should remain where it is, and then reset to "0" and then reset to the point when it syncs
        - Need to check history of the same during relocate operation
    - Report per-volume from VRG
    - Report lastGroupSyncTime from VRG
      - For metrics data on a managed cluster
    - Report  lastGroupSyncTime from DRPC
      - For data on the hub
  - Code mechanics:
    - lastSyncTime or lastGroupSyncTime is reported as a metric in places where it is updated in the code

References:
  - Naming and labels: https://prometheus.io/docs/practices/naming/
  - More on labels:
    - https://prometheus.io/docs/practices/instrumentation/#use-labels
    - https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels
  - Timestamp guidelines: https://prometheus.io/docs/practices/instrumentation/#timestamps-not-time-since
  - Metric types: https://prometheus.io/docs/concepts/metric_types/

**Comment by GowthamShanmugam** [comment]
UI Requirements:
 1) To raise the SLA alert, We need to compare the SLA taken with the scheduled interval. For that this one metric is not enough. We need another metric that has DRPolicy scheduled interval as metrics values and both metrics should have a DRPolicy name to join and display alert.
  2) While generating the alert, the user should know for which application they are getting the alert, just adding DRPC info as a label won't be enough. 
     One possible solution is, the UI can provide the application name and application type as annotations or labels in DRPC CR.  So the DR operator can easily add this info as a metrics label. and while raising alert, we can easily add this info inside the alert description.
       When an alert is notified through the alert managers (which is configured by the user manually) they will get meaning full alert.  

cc: @ShyamsundarR and @rakeshgm

**Comment by GowthamShanmugam** [comment]
As per discussion with @rakeshgm UI has to read the lastUpdateTime using Prometheus query(time() - ramen_last_sync_timestamp_seconds). Ref: https://prometheus.io/docs/practices/instrumentation/#timestamps-not-time-since.

One issue with this approach is, if the ramen metrics exporter takes time to push metrics due to the temporary operator down, then the SLA calculation will for wrong. because here UI will consider the metrics reported time as last update time.

**Comment by GowthamShanmugam** [comment]
Alert rule:
```
Recording rule SLA: (time() - ramen_last_sync_timestamp_seconds) / on(drPolicyName) group_left( (dr_policy_sync_interval_seconds)
SLA > 1 and SLA < 2 - Warning
SLA >= 2 -  Critical
```

**Comment by ShyamsundarR** [comment]
A metric as per the initial description is complete, additionally the metric carries a label `policyname` with a value that is the DRPolicy name.

Another metric has been added as follows to help correlate as a single prometheus query for alerts or graphs for a given DRPolicy as follows:
```
ramen_policy_schedule_interval_seconds
Labels:
  - policyname: DRPolicy name
Type: Gauge
Metric: <scheduling interval in seconds>
```

**Comment by GowthamShanmugam** [comment]
(time()-ramen_last_sync_timestamp_seconds) / on(policyname) group_left() (ramen_policy_schedule_interval_seconds)

**Comment by ShyamsundarR** [comment]
This is now done. Marking this as closed.
