### ISSUE TITLE
add delete interface for ManagedClusterViews for garbage collection

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#73]
This came up in PR #57 

Add delete interface for ManagedClusterView so that we can garbage collect MCVs that we no longer need.

Example use case: post failover, once the MCV reports VRG status as Secondary in the failed cluster (preferredCluster), we would then delete the MCV at an appropriate time.

**Comment by ShyamsundarR** [comment]
Resolved by #107
