### ISSUE TITLE
[drenv] Add work-manager addon to managed clusters for ManagedClusterView reconciliation

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#756]
Hub operator creates ManagedClusterView resource on the hub to view VRG existence and status on a managed cluster. This requires [this](https://github.com/stolostron/multicloud-operators-foundation/blob/main/pkg/klusterlet/view/view_controller.go) controller running.

The means to install it is as an addon named "work-manager", say as this patch:
```
diff --git a/test/ocm-cluster/start b/test/ocm-cluster/start
index 7f46ec9..5f10846 100755
--- a/test/ocm-cluster/start
+++ b/test/ocm-cluster/start
@@ -14,6 +14,7 @@ ADDONS = (
     "application-manager",
     "governance-policy-framework",
     "config-policy-controller",
+    "work-manager",
 )
 
 ADDONS_NAMESPACE = "open-cluster-management-agent-addon"
```

Without the above, if an applications PlacementRule (or Placement) is DR protected, DRPC will fail to progress on its initial reconciliation of the resource as it would not find any status for the created ManagedClusterView resource.

**Comment by ShyamsundarR** [comment]
The patch as it stands above fails in ocm-cluster/start:wait as the deployment rolled out to the managed cluster is `klusterlet-addon-workmgr` in the `open-cluster-management-agent-addon` namespace, and the wait looks for a deployment of the same name.

**Comment by ShyamsundarR** [comment]
> The patch as it stands above fails in ocm-cluster/start:wait as the deployment rolled out to the managed cluster is `klusterlet-addon-workmgr` in the `open-cluster-management-agent-addon` namespace, and the wait looks for a deployment of the same name.

A better way to process success of add-on availability on the managed cluster could be to look at the following on the hub cluster, in the managed cluster namespace:
```
$ kubectl get ManagedClusterAddOn -n dr2 work-manager
NAME           AVAILABLE   DEGRADED   PROGRESSING
work-manager   True                   
```

This will delink the wait from the assumption that the name of the deployments are the same as the add-on name.

**Comment by nirs** [comment]
Make sense, I hope that testing on the hub without checking the
actual status on the managed cluster will not bite us later.
