### ISSUE TITLE
Recipe: workflow and volume structs should have default values

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#768]
**Objective**: when the user opts-in to Recipe behavior, use default values for `captureWorkflowName`, `recoverWorkflowName`, and `volumeGroupName` so users only need to specify `kubeObjectProtection.recipeRef.name` to use Recipe Workflows. These fields should remain optional so users can overwrite them with custom ones if desired. The intention is for a user at a hub/DRPC level to need to know as little as possible about a Recipe, which exists at Managed Cluster/VRG level.

**Comment by hatfieldbrian** [comment]
TODO: determine what default values should be for all 3 fields

**Comment by hatfieldbrian** [comment]
Fixed by #836
