### ISSUE TITLE
Add a method to prepare a managed cluster for failover action in the regional DR case

### ISSUE THREAD

**Issue by ShyamsundarR** [RamenDR/ramen#788]
Currently in the case of Ceph-RBD mirroring we need to scale down the RBD mirror deployment on the cluster we are failing over to, before we failover the workload. As a failover would perform a force-promote of the RBD image as primary, this avoids any raciness with the RBD mirror daemon also updating/accessing the image for syncing snapshots.

To ensure such pre-conditions are met before a user initiated failover is orchestrated across the clusters, we need to build some method in the DRCluster/DRPolicy CRD to declare the state that a cluster is a failover target and ensure the target cluster is ready for a failover, before user workloads are failed over to the same.

**Comment by nirs** [comment]
Any details on the "raciness with the RBD mirror daemon" do we have a Ceph bug for this issue?

**Comment by ShyamsundarR** [comment]
> Any details on the "raciness with the RBD mirror daemon" do we have a Ceph bug for this issue?

Unable to find upstream Ceph trackers for the same, but the RHBZ is https://bugzilla.redhat.com/show_bug.cgi?id=2009735

**Comment by ShyamsundarR** [comment]
Fixed by #819 in part. The storage vendor part of acting on a requested MaintenanceMode is being developed here: https://github.com/red-hat-storage/odf-multicluster-orchestrator/pull/161
