### ISSUE TITLE
Improve error message and logs when displaying cluster names

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#795]
When waiting for clusters to become ready times out, we show:

    RuntimeError: Timeout waiting for cluster hub

The error may be confusing if your hub cluster is not named `hub`. Make it more clear:

    RuntimeError: Timeout waiting for cluster 'hub'

This should be used for all cases we show a cluster names in errors or logs.

**Comment by nirs** [comment]
@Shwetha-Acharya do you want to take this issue? This is a good learning task, and
add value to users of the tool.

**Comment by Shwetha-Acharya** [comment]
> @Shwetha-Acharya do you want to take this issue? This is a good learning task, and add value to users of the tool.

yes @nirs I will take it up
