### ISSUE TITLE
Ramen s3Secret not deployed on the manged clusters in test env

### ISSUE THREAD

**Issue by nirs** [RamenDR/ramen#818]
ramen-config disables `deploymentAutomationEnabled` in ramen configmap since it does not
install the catalog for olm installation. This seems to break s3 secret distribution.

The installed ramen configmap:

```
$ kubectl get cm ramen-hub-operator-config -n ramen-system --context hub -o yaml
...
    drClusterOperator:
      deploymentAutomationEnabled: false
      s3SecretDistributionEnabled: true
...
```

With this configuration, after deploying the sample application, the vrg does not show
the current state, and in the logs we see that ramen cannot access minio. And indeed the
s3Secret does not exist on the managed clusters.

Enabling `deploymentAutomationEnabled` on the hub fixes this issue - the s3Secret are
distributed to the managed clusters, and the vrg becomes ready.

Fix:

- [ ] Try to enable `deploymentAutomationEnabled` in test/ramen-config/deploy
  - this is the right way anyway for a real deployment
  - note: this may break since we don't install the olm catalog
- [ ] Maybe there is a bug in ramen - looks like `s3SecretDistributionEnabled` depends on `deploymentAutomationEnabled`. Since we always enable `deploymentAutomationEnabled` maybe we missed this bug.

**Comment by rakeshgm** [comment]
we need `s3SecretDistributionEnabled` and `s3SecretDistributionEnabled` to be true. 
https://github.com/RamenDR/ramen/blob/main/controllers/drpolicy.go#L46

**Comment by ShyamsundarR** [comment]
jFYI, Implementation is to distribute secrets only if deployment automation is enabled, IOW, for secret distribution the deployment automation should also be enabled.

**Comment by nirs** [comment]
Ok, checking if enabling deploymentAutomationEnabled works, if not we need to add the catalog stuff.

**Comment by ShyamsundarR** [comment]
It maybe easier to create the secrets on the ManagedClusters when using `make deploy` in the drenv case. I.e instead of relying on OCM configuration policy (which is used internally in the code to create the same secret as in the hub, on the managed clusters) the script can create the secret in the ramen operator namespace on all the cluster, which this configuration setting is off.
