### ISSUE TITLE
vrg is set to primary before kube resources getting protected

### ISSUE THREAD

**Issue by njjry** [RamenDR/ramen#867]
When testing CPD, I found for the failover of cpd-instance ns, the vrg status is set to primary before the recovery hook's execution is completed and kubernetes resources getting protected.

**Comment by hatfieldbrian** [comment]
I reviewed the Kube objects recovery path and did not find a case where some Kube objects are recovered, but `ClusterDataReady` is not set to false.  @njjry If this issue occurs again, please capture VRG and paste it here.  The ramen log may also be helpful.  Thank you.

**Comment by hatfieldbrian** [comment]
A VRG's `status.state` is set to its `spec.replicationState` when its `DataReady` condition is true:
https://github.com/RamenDR/ramen/blob/407e3d93b8a07e450be255cc57b0236b7a91efbb/controllers/volumereplicationgroup_controller.go#L1042-L1043
Its `ClusterDataProtected` condition need not be true.
