### ISSUE TITLE
KubeObjectProtection: VR ownerReferences not restored after Failover

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#884]
When using KubeObjectProtection (without a Recipe) with Regional DR, VR ownerReferences are not restored on the Recovery Cluster after Failover. This causes the Recovery Cluster VRG to miss reconciles on Relocate/Failback when the VR changes state; this results in the VRG hanging when transitioning to Secondary during the Relocate procedure found [here](https://github.com/RamenDR/ramen/blob/c3f6a67adf9ad7acdb421e14659768eafa369065/docs/vrg-usage.md#failbackrelocate-application-from-cluster2-to-cluster1).

**Steps to reproduce:**
1. Setup environment with 2 managed clusters, no hub, regional DR (Minikube is fine); cluster1=Home, cluster2=Recovery.
2. Protect Busybox application with Ramen KubeObjectProtection on cluster1 (no Recipe required)
3. Failover application to cluster2
4. Attempt to failback/relocate app to cluster1

**Expected output**: application is restored to cluster1
**Actual output**: cluster2 never transitions to Secondary state ([step 11](https://github.com/RamenDR/ramen/blob/c3f6a67adf9ad7acdb421e14659768eafa369065/docs/vrg-usage.md#failbackrelocate-application-from-cluster2-to-cluster1)), so failback never completes

**Suspected issue**: VRG never transitions to Secondary because it waits on VR to transition to Secondary, but misses the VR transition because ownerReferences are not present on the Recovery Cluster VR after Failover.

**Workaround**: once VR on cluster2 has become Secondary, add an annotation to the cluster2 VRG to trigger a reconcile (this will not update the generation number, whereas updating the spec will). VRG will be updated to Secondary and Failover/Relocate will continue.

**Proposed solutions**:
1. Exclude VRs from all Restore operations. Issues: may not be in keeping with user desires.
2. Exclude VRs from all Backup operations. Issues: may not be in keeping with user desires.
3. Find some other way to connect/add ownerReferences to VR from VRG manually.

VR after application on cluster1, pre-failover:
```yaml
apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeReplication
metadata:
  creationTimestamp: "2023-05-11T22:36:43Z"
  finalizers:
  - replication.storage.openshift.io
  generation: 1
  name: busybox-pvc
  namespace: recipe-test
  ownerReferences:
  - apiVersion: ramendr.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: VolumeReplicationGroup
    name: bb
    uid: 90b8c008-eb96-47dc-82e9-1ef79f9a38c1
  resourceVersion: "14641767"
  uid: ee709c9f-d5d2-4d02-8916-0692dd57afd7
spec:
# omitted
```

VR after failover to cluster2, post-restore:
```yaml
apiVersion: replication.storage.openshift.io/v1alpha1
kind: VolumeReplication
metadata:
  creationTimestamp: "2023-05-11T22:51:35Z"
  finalizers:
  - replication.storage.openshift.io
  generation: 1
  labels:
    velero.io/backup-name: recipe-test--bb--0----minio-cluster1
    velero.io/restore-name: recipe-test--bb--0
  name: busybox-pvc
  namespace: recipe-test
  resourceVersion: "13927852"
  uid: 5f28925d-90da-4bbe-b517-c527d5ea60f4
spec:
# omitted
```

**Comment by ShyamsundarR** [comment]
> **Workaround**: once VR on cluster2 has become Secondary, add an annotation to the cluster2 VRG to trigger a reconcile (this will not update the generation number, whereas updating the spec will). VRG will be updated to Secondary and Failover/Relocate will continue.
> 
> **Proposed solutions**:
> 
>     1. Exclude VRs from all Restore operations. Issues: may not be in keeping with user desires.
> 
>     2. Exclude VRs from all Backup operations. Issues: may not be in keeping with user desires.
> 
>     3. Find some other way to connect/add ownerReferences to VR from VRG manually.

This problem of ownerRef MAY exist for other k8s resources that are backed up and that further create child resources (for example a deployment that creates a replicaset and pods (not stating this will have the problem, but a use-case)).

VRG expects to create the VR and hence have the desired ownerRef on it. I see the best way forward as not backing up the VRs (IOW (2) above) and let the reconciler decide when it wants to create the resource on the target cluster. Actually we potentially do not want to backup the VRG even?

An owner ref also holds the UID of the object that is the referent, which would change as we restore a VRG. For recreating the owneRef to the VR, we potentially need to take care to ensure the VR really belongs to the VRG that is being created.

**Comment by hatfieldbrian** [comment]
PR #898
