### ISSUE TITLE
Improve DRPC status update logic

### ISSUE THREAD

**Issue by BenamarMk** [RamenDR/ramen#888]
Currently, the DRPC status is being updated regardless of whether any changes have occurred. This behavior leads to unnecessary updates and it impacts the UI performance. This issue is to ensure that the DRPC status update logic is only updated when there are actual changes.

**Comment by GowthamShanmugam** [comment]
I have observed, DRPC CR gets updated again and again even when no status change is detected. only three fields keep changing lastUpdateTime, resourceVersion, and time under managedFields, and UI watcher is keep triggered due to this behavior.
