### ISSUE TITLE
PVC remain in pending state after successful failover

### ISSUE THREAD

**Issue by pdumbre** [RamenDR/ramen#943]
Steps to reproduce:
Initiate failover of an application on cluster where earlier PVCs in terminating state which is needed while changing ReplicationState of vrg to secondary.
After successful failover, PVCs in pending state.
Observed that UID field of PV in 'ClaimRef' not refreshed.

**Comment by hatfieldbrian** [comment]
Is there any chance that this runtime type check fails?
https://github.com/RamenDR/ramen/blob/e2562bf6924eb284de95a2b4b163ff3aa9ac6ffe/controllers/vrg_volrep.go#L2073C1-L2074C1

**Comment by ShyamsundarR** [comment]
As this is a VRG only environment, answering/asking this from a hub/DRPC+VRG perspective:

- The DRPC would wait for the older failed cluster to report a cleaned state before starting a failover to the same, IOW the cleanup ensures that VRG is secondary on the older cluster and its status reflects that all required conditions to reach secondary are met
- Further post the cluster reports Secondary, VRG is deleted on that cluster, which ensures that the PVCs/VRs etc are also cleaned up
- In the case you mention, it seems like VRG was either marked secondary and was left as is, before initiating a further failover, which can result in the consequences that you mention

Request some clarification regarding the same, thanks.

**Comment by pdumbre** [comment]
As a part of fusion 'relocation' workflow, before starting relocation on new cluster, VRG ReplicationState on older cluster is updated as 'secondary' and PVCs are also marked for deletion. 
When failback is initiated again on older cluster (for application relocated to new cluster), older vrg(having secondary ReplicationState) is deleted and new vrg is created. Along with older vrg, PVC also gets automatically deleted since its already marked for deletion.
Before starting relocation on given cluster where we faced PVC pending issue, following was VRG and PVC status
1. VRG having ReplicationState as secondary
2. PVCs in terminating state.
