### ISSUE TITLE
Retrieving VRG from MCV is returning NotFound error where the object exists

### ISSUE THREAD

**Issue by BenamarMk** [RamenDR/ramen#95]
getVRGFromManagedCluster is not behaving as expected.  The VRG exists in the managed cluster, but the error returned is NotFound.

**Comment by ShyamsundarR** [comment]
@BenamarMk This is resolved post changes to condition checks for MCV?

**Comment by ShyamsundarR** [comment]
Possibly linked to https://github.com/RamenDR/ramen/issues/254 as well

**Comment by ShyamsundarR** [comment]
Closing this as #254 is also root caused.
