### ISSUE TITLE
Measure and graph velero backup and restore system performance impact varying API server object count, types, and sizes

### ISSUE THREAD

**Issue by hatfieldbrian** [RamenDR/ramen#973]
- [ ] Verify fix for backup time is still there and within expected performance
- [ ] Debug restore time outliers (why is it taking an hour for 10 resources, 2-3 took 40-45 minutes total)
- ~~Prepare presentation for Kubecon?  Acceptance/Rejection notice expected by Aug 1 at latest~~

**Comment by ShyamsundarR** [comment]
Closing issue, required optimizations are in place as per comments.
