### ISSUE TITLE
Makefile require operator-sdk version 1.10 even when existing version is installed

### ISSUE THREAD

**Issue by tjanssen3** [RamenDR/ramen#975]
## Context
I experienced a difficult-to-debug issue that involved my operator-sdk version being the wrong version. I'd like to avoid others experiencing this, so I'm opening an issue to resolve it later.

## Issue
Operator-SDK is required by Ramen for several `make` commands. Implicitly, a version is required, but it is not checked or mandated. There is an existing check to make sure operator-sdk is on the system, but if an existing version is found and is incorrect, this will pass undetected.

## Task
In `Makefile`, check for the `operator-sdk` version number and if it does not match the correct version number, install the correct version.

### Examples of operator-sdk versions
On commit ID `0bf0b822e45336be68788871ab2b565859e4eeee`, this was the problematic version:
```bash
$ operator-sdk version
operator-sdk version: "v1.4.2", commit: "4b083393be65589358b3e0416573df04f4ae8d9b", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"
```

The correct version is: 
```bash
$ operator-sdk version
operator-sdk version: "v1.10.0", commit: "c247d4b4142cd7736f122796e3388fbd05f62b71", kubernetes version: "1.20.2", go version: "go1.16.6", GOOS: "linux", GOARCH: "amd64"
```

**Comment by hatfieldbrian** [comment]
Labeled low priority because the impact is limited to Ramen developer productivity.

**Comment by ShyamsundarR** [comment]
Should be resolved with changes in Makefile and file `hack/install-operator-sdk.sh`
