### ISSUE TITLE
CI: Node12 has been out of support 

### ISSUE THREAD

**Issue by Shwetha-Acharya** [RamenDR/ramen#987]
We are encountering warnings such as:

The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2,
actions/setup-go@v2.

Refer warnings at the end:
https://github.com/RamenDR/ramen/actions/runs/5582186941

More information about this  can be found at:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by nirs** [comment]
More info is good - but we need the minimal info here:\
- What is the issue?
- Who is affected?
- Is this random failure? reproducible?
- Known workaround?
- Suggested solution?
