### ISSUE TITLE
CI: Golangci Lint Cannot open: File exists errors 

### ISSUE THREAD

**Issue by Shwetha-Acharya** [RamenDR/ramen#993]
With the following change: https://github.com/Shwetha-Acharya/ramen/commit/651cb38ccfce24fdd455239b0ca80358664af3e0 very first run did not produce any  "Cannot open" errors:
https://github.com/Shwetha-Acharya/ramen/actions/runs/5586010547

However, on subsequent run which just had altered commit message, these warnings and errors started to appear:
https://github.com/Shwetha-Acharya/ramen/actions/runs/5587479487

**Comment by Shwetha-Acharya** [comment]
> > Refer https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ to know more about built image warnings.
> 
> I did not see any build image warnings - how is this related to the golangci errors?

They are not related to golangci errors, these warnings were also coming up with golangci errors while I was testing, so I had grouped them together.

**Comment by nirs** [comment]
This error:

> Publish built imageThe `save-state` command is deprecated and will be disabled soon. Please > upgrade to using Environment Files. For more information see: > https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show more

Is not related to the golangci error - this comes from a different job.

Lets keep issues focums on one type of error. Please open another issue for the publish image warning.

**Comment by Shwetha-Acharya** [comment]
> This error:
> 
> > Publish built imageThe `save-state` command is deprecated and will be disabled soon. Please > upgrade to using Environment Files. For more information see: > https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/Show more
> 
> Is not related to the golangci error - this comes from a different job.
> 
> Lets keep issues focums on one type of error. Please open another issue for the publish image warning.

Okay I will create seperate issue for it
